In [1]:
import numpy as np
import pandas as pd

In [2]:
# creating a pandas series from a simple list

In [3]:
sci_consts = [ 3.14, 2.718, 6.69, 2.999 ]

In [4]:
type(sci_consts)

list

In [5]:
mysr = pd.Series(sci_consts) 

In [6]:
mysr

0    3.140
1    2.718
2    6.690
3    2.999
dtype: float64

In [7]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [8]:
pd.Series(digits)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [9]:
# strings are considred as objects
# even if one string present in list then whole list considered as object

In [10]:
names = ["Hari","Manu","Abin"]

In [11]:
pd.Series(names)

0    Hari
1    Manu
2    Abin
dtype: object

In [12]:
 # peresence of one float causes internal conversion to float 

In [13]:
mix1 = [0, 2, 3.23] # dtype: float64

In [14]:
pd.Series(mix1) # by default the indexes will start from zero to n-1

0    0.00
1    2.00
2    3.23
dtype: float64

In [15]:
mix2 = [1,2,"hi"] # dtype: object

In [16]:
pd.Series(mix2)

0     1
1     2
2    hi
dtype: object

In [17]:
# creating an array of random numbers in range [0,1)

In [18]:
random_nums = np.random.rand(15) 

In [19]:
random_nums

array([0.97794743, 0.39516949, 0.41894379, 0.5601118 , 0.90867509,
       0.66454558, 0.65291054, 0.83228341, 0.11269044, 0.97783545,
       0.09191105, 0.1966318 , 0.56080553, 0.95807783, 0.32277718])

In [20]:
rand_series = pd.Series(random_nums)

In [21]:
rand_series

0     0.977947
1     0.395169
2     0.418944
3     0.560112
4     0.908675
5     0.664546
6     0.652911
7     0.832283
8     0.112690
9     0.977835
10    0.091911
11    0.196632
12    0.560806
13    0.958078
14    0.322777
dtype: float64

In [22]:
type(rand_series)

pandas.core.series.Series

In [23]:
myarr = np.arange(1,30+1).reshape(6,5) # an array having 1 to 30 numbers

In [24]:
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
myarr.size

30

In [26]:
myarr.shape

(6, 5)

In [27]:
mydf = pd.DataFrame(myarr, index = range(6)) 

In [28]:
mydf

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30

In [29]:
np.linspace(0.1,1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
"""index = np.linspace(0.1,0.5,5)""" 

'index = np.linspace(0.1,0.5,5)'

In [31]:
testdf = pd.DataFrame(np.empty((9,5),dtype=int), index = np.linspace(0.2, 1.8, 9))

In [32]:
testdf.columns = ("A","B","C","D","E") # changing the index of the columns

In [33]:
testdf

A                B                C                D  \
0.2   93918491199747                0  140665488707120  140665488508656   
0.4  140665466399872  140665487922928  140665466519488  140665488103536   
0.6  140665466585200  140665466585392  140665466585648  140665466585840   
0.8  140665488233584  140665488885232  140665466586160  140665466586224   
1.0  140665466586416  140665466586480  140665466586736  140665466586816   
1.2  140665487928304  140665487922224  140665487922288  140665487922352   
1.4  140665487350256  140665486939120  140665487918256  140665488230384   
1.6  140665486725040  140665487419440  140665465699120  140665488507824   
1.8  140665488357424  140665487929392  140665488241584  140665487930928   

                   E  
0.2  140665466519344  
0.4  140665487929712  
0.6  140665466573392  
0.8  140665477780208  
1.0  140665487922160  
1.2  140665487922096  
1.4  140665487884464  
1.6  140665488503664  
1.8              368

In [34]:
# Acessing the values

In [35]:
testdf['A'][0.4]

140665466399872

In [36]:
testdf.T # taking transpose of the dataframe

0.2              0.4              0.6              0.8  \
A   93918491199747  140665466399872  140665466585200  140665488233584   
B                0  140665487922928  140665466585392  140665488885232   
C  140665488707120  140665466519488  140665466585648  140665466586160   
D  140665488508656  140665488103536  140665466585840  140665466586224   
E  140665466519344  140665487929712  140665466573392  140665477780208   

               1.0              1.2              1.4              1.6  \
A  140665466586416  140665487928304  140665487350256  140665486725040   
B  140665466586480  140665487922224  140665486939120  140665487419440   
C  140665466586736  140665487922288  140665487918256  140665465699120   
D  140665466586816  140665487922352  140665488230384  140665488507824   
E  140665487922160  140665487922096  140665487884464  140665488503664   

               1.8  
A  140665488357424  
B  140665487929392  
C  140665488241584  
D  140665487930928  
E              368

In [37]:
newdf = pd.DataFrame(np.random.rand(300,6),index = np.arange(300))

In [38]:
newdf

0         1         2         3         4         5
0    0.344422  0.926697  0.778187  0.274398  0.343690  0.458606
1    0.223485  0.347856  0.465580  0.108333  0.369583  0.595442
2    0.168075  0.676383  0.410130  0.704352  0.578163  0.199384
3    0.342149  0.309322  0.309085  0.051587  0.294236  0.859212
4    0.901422  0.060224  0.851643  0.018221  0.033832  0.320243
..        ...       ...       ...       ...       ...       ...
295  0.998935  0.378079  0.596371  0.512926  0.514446  0.901336
296  0.735239  0.143443  0.122653  0.053561  0.752470  0.527585
297  0.780893  0.672075  0.677806  0.985171  0.026632  0.788937
298  0.643694  0.917853  0.336956  0.051020  0.486341  0.456941
299  0.341368  0.423533  0.986259  0.021008  0.471760  0.457408

[300 rows x 6 columns]

In [39]:
type(newdf)

pandas.core.frame.DataFrame

In [40]:
newdf.describe()

0           1           2           3           4           5
count  300.000000  300.000000  300.000000  300.000000  300.000000  300.000000
mean     0.516159    0.476536    0.529062    0.477105    0.497846    0.500906
std      0.273147    0.281630    0.299643    0.277983    0.288400    0.281591
min      0.000173    0.003061    0.000149    0.003200    0.001737    0.000184
25%      0.279139    0.236748    0.248327    0.242421    0.236596    0.269728
50%      0.531930    0.448920    0.538922    0.482931    0.519210    0.493485
75%      0.753957    0.695137    0.789107    0.683587    0.750155    0.755577
max      0.998935    0.999580    0.992369    0.992614    0.995432    0.996836

In [41]:
newdf.head(8)

0         1         2         3         4         5
0  0.344422  0.926697  0.778187  0.274398  0.343690  0.458606
1  0.223485  0.347856  0.465580  0.108333  0.369583  0.595442
2  0.168075  0.676383  0.410130  0.704352  0.578163  0.199384
3  0.342149  0.309322  0.309085  0.051587  0.294236  0.859212
4  0.901422  0.060224  0.851643  0.018221  0.033832  0.320243
5  0.706156  0.396901  0.078843  0.783731  0.001737  0.223744
6  0.649125  0.161890  0.066613  0.775399  0.541802  0.034465
7  0.398451  0.891473  0.259242  0.119087  0.129747  0.049299

In [42]:
newdf.tail(8)

0         1         2         3         4         5
292  0.160110  0.458284  0.960899  0.097131  0.946460  0.404372
293  0.413518  0.672250  0.947116  0.736484  0.212964  0.642239
294  0.933953  0.793277  0.124639  0.620223  0.544128  0.376710
295  0.998935  0.378079  0.596371  0.512926  0.514446  0.901336
296  0.735239  0.143443  0.122653  0.053561  0.752470  0.527585
297  0.780893  0.672075  0.677806  0.985171  0.026632  0.788937
298  0.643694  0.917853  0.336956  0.051020  0.486341  0.456941
299  0.341368  0.423533  0.986259  0.021008  0.471760  0.457408

In [43]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [44]:
newdf[5][115] 

0.7020523801585512

In [45]:
# mutating the data-frame, raises a warning though
newdf[5][3] = "Hii"
newdf[1][1] = "Tq"

/tmp/ipykernel_73809/732091781.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[1][1] = "Tq"


In [46]:
newdf

0         1         2         3         4         5
0    0.344422  0.926697  0.778187  0.274398  0.343690  0.458606
1    0.223485        Tq  0.465580  0.108333  0.369583  0.595442
2    0.168075  0.676383  0.410130  0.704352  0.578163  0.199384
3    0.342149  0.309322  0.309085  0.051587  0.294236       Hii
4    0.901422  0.060224  0.851643  0.018221  0.033832  0.320243
..        ...       ...       ...       ...       ...       ...
295  0.998935  0.378079  0.596371  0.512926  0.514446  0.901336
296  0.735239  0.143443  0.122653  0.053561  0.752470  0.527585
297  0.780893  0.672075  0.677806  0.985171  0.026632  0.788937
298  0.643694  0.917853  0.336956  0.051020  0.486341  0.456941
299  0.341368  0.423533  0.986259  0.021008  0.471760  0.457408

[300 rows x 6 columns]

In [47]:
newdf.dtypes

0    float64
1     object
2    float64
3    float64
4    float64
5     object
dtype: object

In [48]:
newdf.columns

RangeIndex(start=0, stop=6, step=1)

In [49]:
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [50]:
myarr.T # taking transpose of an array

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [51]:
arrdf = pd.DataFrame(myarr)

In [52]:
arrdf

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30

In [53]:
arrdf.loc[0] # returns first row

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64

In [54]:
arrdf.loc[0, 2] # returns first row, third column

3

In [55]:
arrdf.loc[0,5] = 123 # non- =existent column will be created

In [56]:
arrdf

0   1   2   3   4      5
0   1   2   3   4   5  123.0
1   6   7   8   9  10    NaN
2  11  12  13  14  15    NaN
3  16  17  18  19  20    NaN
4  21  22  23  24  25    NaN
5  26  27  28  29  30    NaN

In [57]:
arrdf.drop(5, axis = 0) # axis 0 refers to rows and index 5 means row index 5

0   1   2   3   4      5
0   1   2   3   4   5  123.0
1   6   7   8   9  10    NaN
2  11  12  13  14  15    NaN
3  16  17  18  19  20    NaN
4  21  22  23  24  25    NaN

In [58]:
arrdf.drop(5, axis = 1) # axis 1 refers to column and index 5 means column index 5

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30

In [59]:
arrdf.columns = ['a', 'b', 'c', 'd', 'e', 'f']

In [60]:
arrdf

a   b   c   d   e      f
0   1   2   3   4   5  123.0
1   6   7   8   9  10    NaN
2  11  12  13  14  15    NaN
3  16  17  18  19  20    NaN
4  21  22  23  24  25    NaN
5  26  27  28  29  30    NaN

In [61]:
arrdf.loc[[1,3],['b','d']] # specific portion of the data frame

b   d
1   7   9
3  17  19